version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
      MYSQL_DATABASE: db_todo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3303:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      springboot-mysql-net:
  app:
    container_name: app
    depends_on:
      - api
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 4200:80
    networks:
      springboot-mysql-net:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    depends_on:
      - mysqldb
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/db_todo
      - spring.datasource.username=springuser
      - spring.datasource.password=ThePassword
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net:
volumes:
  mysql-data:
